config/routes.rb
Rails.application.routes.draw do
  root :to => "home#index"
  post '/home/update_board_tile_color'
  get '/home/reload_tiles'
  get '/home/userboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/palette.rb
class Palette < ApplicationRecord
  belongs_to :user
  validates_presence_of :code,:row,:column,:user_id

  def self.find_color_code_and_user_details(x,y)
    result = []
    palette = Palette.where(row: x,column: y).last
    result = [palette.code,"#{palette.user.username} #{palette.form_details}"] if palette.present?
    result
  end

  def form_details
    self.updated_at.strftime("%d-%m-%Y %H:%M:%S")
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :palettes,dependent: :destroy
  validates_presence_of :username,:ip_address

  def find_favourite_color
   self.palettes.group(:code).count.sort {|a1,a2| a2[1]<=>a1[1]}.first[0]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_user_name

  include ApplicationHelper

  def index
  end

  def update_board_tile_color
    params.permit!
    params[:tiles].split(",").each do |tile|
      position = tile.split("-")[1].split("_")
      @user.palettes.create(code: params[:color_code],row: position[0],column: position[1])
    end
    respond_to :js
  end

  def reload_tiles
    respond_to :js
  end

  def userboard
    @users = User.joins(:palettes)
                 .select("users.*, count(palettes.id) as scount")
                 .group("users.id")
                 .order("scount DESC")
  end

  protected

  def set_user_name
    user = User.where(ip_address: request.remote_ip).last
    if user.present?
      @user = user
    else
      username = "Admin #{DateTime.now.strftime('%Y:%m:%d %H:%S')}"
      @user = User.create(username: username,ip_address: request.remote_ip)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def get_tile_details(row,col)
    Palette.find_color_code_and_user_details(row,col)
  end

  def generate_tile(row,col)
    tile_info = get_tile_details(row,col)
    raw("<div onclick='toggleClass(this);' class='content' 
         id='tile-#{row}_#{col}' #{style_attributes(tile_info)}></div>")
  end

  def style_attributes(tile_info)
    "style='background-color: #{tile_info[0]}' title='#{tile_info[1]}'"
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
Welcome <%= @user.username%>!
<p>
<%= link_to "Grid Picker",root_path%>
</p>
<%= link_to "User List",home_userboard_path%>

app/views/home/_tiles.html.erb
<table>
  <%for row in 1..20 do %>
   <tr>
    <% for col in 1..20 do%>
      <td><%= generate_tile(row,col)%></td>
    <%end%>
   </tr>
  <%end%>
</table>

app/views/home/index.html.erb
<div id="tiles">
  <%= render partial: "tiles"%>
</div>
<br/>
<div class="ml300">
  Color Picker: <input class="colors">
</div>
<div class="ml400 mt10">
  <button onclick="updateTileColors();">Ok</button>
  <button>Cancel</button>
</div>

app/views/home/reload_tiles.js.erb
$('#tiles').html("<%= escape_javascript render(:partial => 'home/tiles') %>");

app/views/home/update_board_tile_color.js.erb
$("div.selected").removeClass("selected");

app/views/home/userboard.html.erb
<table class="userboard">
  <thead>
   <tr>
    <td>No</td>
    <td>User</td>
    <td>Tiles Colored</td>
    <td>Fav Color</td>
   </tr>
  </thead>
  <tbody>
   <%@users.each_with_index do |user,index|%>
    <tr>
     <td><%= index+=1%>.</td>
     <td><%= user.username%></td>
     <td><%= user.scount%></td>
     <td style="background-color: <%= user.find_favourite_color%>"></td>
    </tr>
   <%end%>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ColorPaletteBoard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'header'%>
    <%= yield %>
  </body>
</html>